packages:
  - packages/protocol
  - packages/crypto
  - packages/head
  - packages/tentacle
  - packages/arm/*
  - packages/tests
  - packages/voice-broker

ignoredBuiltDependencies:
  - better-sqlite3
  - esbuild
