/**
 * Minimal JSON-RPC client for `codex app-server` (stdio transport).
 *
 * Wire format (verified against codex-cli 0.157.x): one JSON object per line,
 * JSON-RPC 2.0 shaped but WITHOUT the `"jsonrpc"` field. Three message kinds
 * flow server → client:
 *   • responses      `{ id, result }` / `{ id, error }` to our requests
 *   • notifications  `{ method, params }` (turn/item/thread events)
 *   • server requests `{ id, method, params }` that WE must answer
 *     (command/file approvals, dynamic tool calls, user-input questions)
 *
 * The protocol schema is generated by the binary itself:
 *   codex app-server generate-ts --experimental --out <dir>
 */

import { spawn, type ChildProcessWithoutNullStreams } from 'node:child_process';
import { createInterface } from 'node:readline';
import { createLogger } from '../logger.js';

const logger = createLogger('codex-rpc');

export type RpcId = number | string;

export interface RpcNotification {
  method: string;
  params?: unknown;
}

export interface RpcServerRequest {
  id: RpcId;
  method: string;
  params?: unknown;
}

export class CodexRpcError extends Error {
  constructor(message: string, readonly code?: number, readonly data?: unknown) {
    super(message);
    this.name = 'CodexRpcError';
  }
}

interface Pending {
  method: string;
  resolve: (value: unknown) => void;
  reject: (err: Error) => void;
  timer?: NodeJS.Timeout;
}

export interface CodexRpcOptions {
  /** Executable to spawn (absolute path to `codex`, or `node` for test fakes). */
  command: string;
  /** Arguments. Defaults to `['app-server']`. */
  args?: string[];
  env?: NodeJS.ProcessEnv;
  cwd?: string;
  /** Default per-request timeout. 0 disables. */
  requestTimeoutMs?: number;
}

/**
 * One long-lived `codex app-server` child. A single app-server multiplexes any
 * number of threads, so the adapter owns exactly one of these.
 */
export class CodexRpcProcess {
  onNotification: ((n: RpcNotification) => void) | null = null;
  /** Must eventually call `respond`/`respondError` for `req.id`. */
  onServerRequest: ((req: RpcServerRequest) => void) | null = null;
  onExit: ((info: { code: number | null; signal: NodeJS.Signals | null; stderrTail: string }) => void) | null = null;

  private child: ChildProcessWithoutNullStreams | null = null;
  private nextId = 1;
  private pending = new Map<RpcId, Pending>();
  private stderrTail: string[] = [];
  private exited = false;

  constructor(private readonly opts: CodexRpcOptions) {}

  get alive(): boolean {
    return !!this.child && !this.exited && this.child.stdin.writable;
  }

  start(): void {
    if (this.child) return;
    const child = spawn(this.opts.command, this.opts.args ?? ['app-server'], {
      cwd: this.opts.cwd,
      env: this.opts.env ?? process.env,
      stdio: ['pipe', 'pipe', 'pipe'],
      // .cmd shims on Windows need a shell to resolve.
      shell: process.platform === 'win32' && /\.cmd$/i.test(this.opts.command),
    });
    this.child = child;

    const rl = createInterface({ input: child.stdout, crlfDelay: Infinity });
    rl.on('line', (line) => this.handleLine(line));

    child.stderr.setEncoding('utf8');
    child.stderr.on('data', (chunk: string) => {
      for (const l of chunk.split(/\r?\n/)) {
        if (!l) continue;
        this.stderrTail.push(l);
        if (this.stderrTail.length > 40) this.stderrTail.shift();
      }
    });

    child.on('error', (err) => {
      logger.warn({ err: err.message }, 'codex app-server spawn error');
      this.handleExit(null, null, err.message);
    });
    child.on('exit', (code, signal) => this.handleExit(code, signal));
    // Writing to a dead child raises EPIPE asynchronously on stdin.
    child.stdin.on('error', (err) => logger.debug({ err: err.message }, 'codex stdin error'));
  }

  /** Send a request and await its result. */
  request<T = unknown>(method: string, params?: unknown, timeoutMs?: number): Promise<T> {
    if (!this.alive) return Promise.reject(new CodexRpcError(`codex app-server is not running (${method})`));
    const id = this.nextId++;
    return new Promise<T>((resolve, reject) => {
      const entry: Pending = { method, resolve: resolve as (v: unknown) => void, reject };
      const t = timeoutMs ?? this.opts.requestTimeoutMs ?? 0;
      if (t > 0) {
        entry.timer = setTimeout(() => {
          this.pending.delete(id);
          reject(new CodexRpcError(`codex ${method} timed out after ${t}ms`));
        }, t);
      }
      this.pending.set(id, entry);
      this.write({ id, method, ...(params !== undefined && { params }) });
    });
  }

  notify(method: string, params?: unknown): void {
    if (!this.alive) return;
    this.write({ method, ...(params !== undefined && { params }) });
  }

  respond(id: RpcId, result: unknown): void {
    if (!this.alive) return;
    this.write({ id, result });
  }

  respondError(id: RpcId, message: string, code = -32000): void {
    if (!this.alive) return;
    this.write({ id, error: { code, message } });
  }

  async stop(graceMs = 2000): Promise<void> {
    const child = this.child;
    if (!child || this.exited) return;
    const done = new Promise<void>((r) => child.once('exit', () => r()));
    try { child.stdin.end(); } catch { /* ignore */ }
    child.kill('SIGTERM');
    const timer = setTimeout(() => { try { child.kill('SIGKILL'); } catch { /* ignore */ } }, graceMs);
    await done;
    clearTimeout(timer);
  }

  // ── internals ────────────────────────────────────────

  private write(msg: Record<string, unknown>): void {
    try {
      this.child!.stdin.write(JSON.stringify(msg) + '\n');
    } catch (err) {
      logger.debug({ err: (err as Error).message }, 'codex write failed');
    }
  }

  private handleLine(line: string): void {
    const trimmed = line.trim();
    if (!trimmed) return;
    let msg: Record<string, unknown>;
    try {
      msg = JSON.parse(trimmed) as Record<string, unknown>;
    } catch {
      logger.debug({ line: trimmed.slice(0, 200) }, 'codex: non-JSON stdout line ignored');
      return;
    }

    const hasId = msg.id !== undefined && msg.id !== null;
    const method = typeof msg.method === 'string' ? msg.method : undefined;

    if (hasId && method) {
      this.onServerRequest?.({ id: msg.id as RpcId, method, params: msg.params });
      return;
    }
    if (hasId) {
      const pending = this.pending.get(msg.id as RpcId);
      if (!pending) return;
      this.pending.delete(msg.id as RpcId);
      if (pending.timer) clearTimeout(pending.timer);
      if (msg.error) {
        const e = msg.error as { message?: string; code?: number; data?: unknown };
        pending.reject(new CodexRpcError(e.message ?? `codex ${pending.method} failed`, e.code, e.data));
      } else {
        pending.resolve(msg.result);
      }
      return;
    }
    if (method) this.onNotification?.({ method, params: msg.params });
  }

  private handleExit(code: number | null, signal: NodeJS.Signals | null, spawnError?: string): void {
    if (this.exited) return;
    this.exited = true;
    const stderrTail = [spawnError, ...this.stderrTail].filter(Boolean).join('\n');
    for (const [, p] of this.pending) {
      if (p.timer) clearTimeout(p.timer);
      p.reject(new CodexRpcError(`codex app-server exited during ${p.method}`));
    }
    this.pending.clear();
    this.onExit?.({ code, signal, stderrTail });
  }
}
