/**
 * Source of the "kraki bridge" pi extension.
 *
 * pi has no built-in per-call tool-approval round-trip in `--mode rpc`, no way
 * for the model to surface a question card to the operator, and no way to push
 * an image to the operator's device. This one extension bridges all three by
 * riding pi's extension-UI channel and its `registerTool` API — so the pi
 * adapter can offer the same capabilities the claude/copilot adapters do.
 *
 * It provides:
 *  1. A permission GATE — intercepts every (non-capability) tool_call and asks
 *     the host via `ctx.ui.confirm(toolName, inputJson)`. In rpc mode that
 *     surfaces as an `extension_ui_request{method:"confirm"}` the adapter maps
 *     to a Kraki permission card. The extension is deliberately THIN: it does
 *     NOT decide policy. The adapter applies the copilot-aligned policy on the
 *     request (auto-approve silently vs. show a card) using its in-memory mode.
 *  2. `kraki_get_mode` — returns the live permission mode, read from the meta
 *     sidecar the adapter keeps at env `KRAKI_META_FILE`. The mode is the source
 *     of truth; the model calls this before irreversible actions.
 *  3. `kraki_ask` — asks the operator a question (choices or freeform) via
 *     `ctx.ui.select` / `ctx.ui.input`, surfaced as a Kraki question card.
 *  4. `kraki_show_image` — returns an ImageContent block; the adapter extracts
 *     it into the shared attachment pipeline and pushes it to the device.
 *
 * Loaded UNCONDITIONALLY in every mode (mode is enforced by the adapter policy,
 * not by adding/removing the extension), so a mode change never respawns pi.
 *
 * Kept as a string constant (not a separate asset) so it survives the tentacle
 * SEA bundle — esbuild inlines it and the adapter materializes it to disk at
 * runtime. pi's jiti loader aliases `typebox` / `@earendil-works/*` to pi's own
 * node_modules, so the imports below resolve regardless of the file's location.
 */
export const PI_BRIDGE_EXTENSION_SOURCE = String.raw`// AUTO-GENERATED by the Kraki pi adapter. Do not edit by hand.
import { readFileSync } from "node:fs";
import { basename } from "node:path";
import { Type } from "typebox";

// The extension's own capability tools never go through the permission gate —
// they carry their own operator interaction (or are read-only introspection).
const CAPABILITY_TOOLS = new Set(["kraki_get_mode", "kraki_ask", "kraki_show_image"]);

export default function krakiBridge(pi) {
  // ── 1. Permission gate ──────────────────────────────────────────────────
  // Ask the host to confirm every non-capability tool. The ADAPTER decides
  // whether to auto-approve silently or raise a card, based on mode + tool kind.
  pi.on("tool_call", async (event, ctx) => {
    const toolName = event && event.toolName;
    if (!toolName || CAPABILITY_TOOLS.has(toolName)) return;
    // No dialog channel (shouldn't happen in rpc mode). Fail OPEN so the session
    // isn't wedged waiting on a prompt that can never be answered.
    if (!ctx || !ctx.hasUI) return;
    let message;
    try {
      message = JSON.stringify((event && event.input) || {});
    } catch (_err) {
      message = "{}";
    }
    const approved = await ctx.ui.confirm(toolName, message);
    if (!approved) {
      return { block: true, reason: "Denied by operator \u2014 " + toolName + " was not run (kraki permission)." };
    }
  });

  // ── 2. kraki_get_mode ───────────────────────────────────────────────────
  pi.registerTool({
    name: "kraki_get_mode",
    label: "Get Kraki mode",
    description:
      "Return the current Kraki permission mode (safe|discuss|execute|delegate). " +
      "safe = every tool needs operator approval; discuss = only file writes need " +
      "approval (reads/shell run freely, writes to plan.md are allowed); execute/" +
      "delegate = all tools run without approval. Call this before irreversible actions.",
    promptGuidelines: [
      "Call kraki_get_mode before irreversible or destructive actions (deleting files, force-pushing, destructive shell) to confirm the operator has granted you permission to act.",
    ],
    parameters: Type.Object({}),
    async execute() {
      let mode = "discuss";
      try {
        const p = process.env.KRAKI_META_FILE;
        if (p) {
          const meta = JSON.parse(readFileSync(p, "utf8"));
          if (meta && typeof meta.mode === "string") mode = meta.mode;
        }
      } catch (_err) {
        // fall back to the default on any read/parse failure
      }
      return { content: [{ type: "text", text: mode }], details: { mode } };
    },
  });

  // ── 3. kraki_ask ────────────────────────────────────────────────────────
  pi.registerTool({
    name: "kraki_ask",
    label: "Ask operator",
    description:
      "Ask the human operator a question and wait for their answer. Provide " +
      "'choices' for a multiple-choice question, or omit them for a freeform " +
      "answer. Use for decisions, clarifications, or approvals you cannot infer.",
    parameters: Type.Object({
      question: Type.String({ description: "The question to ask the operator." }),
      choices: Type.Optional(
        Type.Array(Type.String(), { description: "Optional multiple-choice options." }),
      ),
    }),
    async execute(_toolCallId, params, _signal, _onUpdate, ctx) {
      if (!ctx || !ctx.hasUI) {
        return { content: [{ type: "text", text: "Error: UI not available (non-interactive mode)." }], details: {} };
      }
      const choices = Array.isArray(params.choices)
        ? params.choices.filter((c) => typeof c === "string" && c.length > 0)
        : [];
      let answer;
      if (choices.length > 0) {
        answer = await ctx.ui.select(params.question, choices);
      } else {
        answer = await ctx.ui.input(params.question);
      }
      if (answer === undefined || answer === null) {
        return { content: [{ type: "text", text: "The operator cancelled the question." }], details: { cancelled: true } };
      }
      return { content: [{ type: "text", text: String(answer) }], details: { answer: String(answer) } };
    },
  });

  // ── 4. kraki_show_image ─────────────────────────────────────────────────
  pi.registerTool({
    name: "kraki_show_image",
    label: "Show image",
    description:
      "Display an image file to the operator on their device. Use for " +
      "screenshots, diagrams, charts, or generated graphics the operator cannot " +
      "otherwise see. Supported formats: PNG, JPEG, WebP, GIF.",
    parameters: Type.Object({
      path: Type.String({ description: "Absolute path to the image file on disk." }),
      caption: Type.Optional(Type.String({ description: "Optional caption shown with the image." })),
    }),
    async execute(_toolCallId, params) {
      let bytes;
      try {
        bytes = readFileSync(params.path);
      } catch (err) {
        return {
          content: [{ type: "text", text: "Error reading image: " + (err && err.message ? err.message : String(err)) }],
          details: { error: true },
        };
      }
      const ext = (basename(params.path).split(".").pop() || "").toLowerCase();
      const mimeType =
        ext === "jpg" || ext === "jpeg" ? "image/jpeg"
        : ext === "webp" ? "image/webp"
        : ext === "gif" ? "image/gif"
        : "image/png";
      const content = [{ type: "image", data: bytes.toString("base64"), mimeType }];
      if (params.caption) content.push({ type: "text", text: params.caption });
      return { content, details: { path: params.path, caption: params.caption, shown: true } };
    },
  });
}
`;
