/**
 * Source of the "kraki tools" pi extension — the single extension the pi adapter
 * always loads (`--extension`). It gives pi Kraki's human-interaction tools plus
 * the per-call permission gate:
 *
 *   • `ask_user(question, choices?)` — blocks until the human answers and
 *     returns their answer as the tool result. Surfaces via `ctx.ui.select`
 *     (choices) / `ctx.ui.input` (free-form), which in `--mode rpc` emit an
 *     `extension_ui_request` the adapter maps to a Kraki question card; the
 *     answer returns as an `extension_ui_response`.
 *   • `kraki_get_mode({query:"current"})` — returns the live Kraki permission mode
 *     (safe|auto|delegate), read from the meta sidecar the adapter
 *     exports as `KRAKI_META_FILE`. Lets the model confirm its permission
 *     envelope before irreversible actions (the adapter is the source of truth).
 *   • permission gate — intercepts every OTHER tool and asks
 *     `ctx.ui.confirm(...)`. The gate is loaded in ALL modes and always fires;
 *     the ADAPTER decides (via Kraki's shared permission policy on
 *     the live mode) whether to auto-approve silently or raise a Kraki card. The
 *     capability tools (ask_user / show_image / show_report / kraki_get_mode)
 *     are whitelisted so they are never permission-prompted (they ARE the human
 *     channel / read-only introspection).
 *
 * Kept as a string constant (not a separate asset) so it survives the tentacle
 * SEA bundle — esbuild inlines it and the adapter materializes it to disk at
 * runtime. `parameters` are plain JSON Schema objects (verified accepted by pi
 * 0.80.2) so the materialized file needs no `typebox` import it couldn't resolve.
 */
import { REPORT_VALIDATOR_SOURCE } from '../report-policy.js';
import { SELF_MANAGEMENT_MATCHER_SOURCE } from '../self-management-guard.js';

export const PI_KRAKI_TOOLS_SOURCE = String.raw`// AUTO-GENERATED by the Kraki pi adapter. Do not edit by hand.
// Registers ask_user + show_image + show_report + kraki_get_mode (Kraki's
// human-interaction & introspection tools) and a per-call permission gate that
// asks the host to confirm every other tool; the adapter applies the mode policy.
import { readFileSync } from "node:fs";
import { isAbsolute, join } from "node:path";
// Capability tools never go through the permission gate — they carry their own
// operator interaction (ask_user/show_image/show_report) or are read-only
// introspection (kraki_get_mode).
const KRAKI_TOOLS = new Set(["ask_user", "show_image", "show_report", "kraki_get_mode"]);

${REPORT_VALIDATOR_SOURCE}

${SELF_MANAGEMENT_MATCHER_SOURCE}

export default function krakiTools(pi) {
  pi.registerTool({
    name: "ask_user",
    label: "Ask the user",
    description:
      "Ask the human operator a question and BLOCK until they answer. Returns the " +
      "user's answer as the tool result. Provide 'choices' for a multiple-choice " +
      "question, or omit them for a free-form answer.",
    promptGuidelines: [
      "Use ask_user whenever you need a decision, clarification, or missing " +
      "information from the user. The return value is their literal answer.",
    ],
    parameters: {
      type: "object",
      properties: {
        question: { type: "string", description: "The question to ask the user." },
        choices: { type: "array", items: { type: "string" }, description: "Optional multiple-choice options." },
      },
      required: ["question"],
      additionalProperties: false,
    },
    async execute(_id, params, signal, _onUpdate, ctx) {
      const q = String((params && params.question) || "");
      const choices = params && Array.isArray(params.choices) ? params.choices : null;
      if (!ctx || !ctx.hasUI) {
        return { content: [{ type: "text", text: "(no UI available to ask the user)" }], details: {} };
      }
      let answer;
      if (choices && choices.length) {
        answer = await ctx.ui.select(q, choices, { signal });
      } else {
        answer = await ctx.ui.input(q, "", { signal });
      }
      if (answer == null) {
        return { content: [{ type: "text", text: "(the user did not answer)" }], details: { cancelled: true } };
      }
      let decoded = null;
      try {
        const value = JSON.parse(String(answer));
        if (value && value.__krakiAnswer === 1) decoded = value;
      } catch (_err) {
        // Legacy/non-Kraki UI response: use the raw string below.
      }
      if (!decoded) {
        const text = String(answer);
        return { content: [{ type: "text", text }], details: { answer: text } };
      }
      const text = typeof decoded.text === "string" ? decoded.text : "";
      const content = [];
      if (text) content.push({ type: "text", text });
      const images = Array.isArray(decoded.images) ? decoded.images : [];
      for (const image of images) {
        if (image && typeof image.data === "string" && typeof image.mimeType === "string") {
          content.push({ type: "image", data: image.data, mimeType: image.mimeType });
        }
      }
      if (content.length === 0) content.push({ type: "text", text: "The user answered with an image." });
      return { content, details: { answer: text, imageCount: images.length } };
    },
  });

  pi.registerTool({
    name: "show_image",
    label: "Show image to user",
    description:
      "Display an image to the user in the Kraki chat. Use this to visually present " +
      "something the user cannot already see \u2014 a screenshot, diagram, chart, or " +
      "generated graphic. Provide the path to an image file on disk (PNG, JPEG, WebP, " +
      "GIF). For images you only need to inspect yourself, use the read tool instead.",
    promptGuidelines: [
      "Only call show_image when the user would gain new information from seeing the " +
      "image (e.g. a chart or diagram you just generated). Do NOT echo back an image " +
      "the user just sent you \u2014 they can already see it.",
    ],
    parameters: {
      type: "object",
      properties: {
        path: { type: "string", description: "Absolute or cwd-relative path to the image file to display." },
        caption: { type: "string", description: "Optional caption shown with the image." },
      },
      required: ["path"],
      additionalProperties: false,
    },
    async execute(_id, params) {
      const p = String((params && params.path) || "");
      const caption = params && params.caption ? String(params.caption) : "";
      if (!p) {
        throw new Error("show_image: no path provided");
      }
      const abs = isAbsolute(p) ? p : join(process.cwd(), p);
      let bytes;
      try {
        bytes = readFileSync(abs);
      } catch (err) {
        const msg = (err && err.message) || String(err);
        throw new Error("show_image: cannot read " + abs + " \u2014 " + msg);
      }
      const ext = (abs.split(".").pop() || "").toLowerCase();
      const mimeType =
        ext === "png" ? "image/png" :
        ext === "webp" ? "image/webp" :
        ext === "gif" ? "image/gif" : "image/jpeg";
      const content = [];
      if (caption) content.push({ type: "text", text: caption });
      content.push({ type: "image", data: bytes.toString("base64"), mimeType });
      return { content, details: { shown: abs, mimeType } };
    },
  });

  pi.registerTool({
    name: "show_report",
    label: "Show report",
    description:
      "Show a written report to the user in Kraki's report viewer, attached to this message. " +
      "A report is a document: prose, headings, tables, code, inline SVG and Mermaid diagrams " +
      "(write <pre class=\"mermaid\">...</pre>; Kraki renders Mermaid itself). It is NOT a web " +
      "browser: web pages, apps, prototypes, videos and media galleries do not work here. If the " +
      "user asks to open something in a browser, open it with the shell (e.g. open file.html on " +
      "macOS) instead. Limits: at most 1 MB, no video or audio, no external resources, no inlined " +
      "JavaScript libraries, at most 200 KB of embedded raster images (use show_image for screenshots).",
    promptGuidelines: [
      "Use show_report for analysis, design and investigation write-ups the user should read. " +
      "Keep reports text-first and draw diagrams as Mermaid source or small inline SVG, not screenshots.",
      "Inside HTML, escape <, > and & in Mermaid source as &lt; &gt; &amp; (for example class " +
      "stereotypes such as &lt;&lt;interface&gt;&gt;), otherwise the browser parses them as tags.",
      "Do not use show_report to open or preview a web page or app, or when the user asks to open " +
      "something in a browser; run the shell open command for that.",
    ],
    parameters: {
      type: "object",
      properties: {
        path: { type: "string", description: "Absolute or cwd-relative path to the report's .html file." },
        title: { type: "string", description: "Optional report title shown in the report viewer." },
      },
      required: ["path"],
      additionalProperties: false,
    },
    async execute(_id, params) {
      const p = String((params && params.path) || "");
      const requestedTitle = params && params.title ? String(params.title).trim() : "";
      if (!p) throw new Error("show_report: no path provided");
      const abs = isAbsolute(p) ? p : join(process.cwd(), p);
      const lower = abs.toLowerCase();
      if (!lower.endsWith(".html") && !lower.endsWith(".htm")) {
        throw new Error("show_report: path must end in .html or .htm");
      }
      let bytes;
      try {
        bytes = readFileSync(abs);
      } catch (err) {
        const msg = (err && err.message) || String(err);
        throw new Error("show_report: cannot read " + abs + " — " + msg);
      }
      const problem = krakiValidateReport(bytes);
      if (problem) throw new Error("show_report: " + problem + " Fix the file and call show_report again.");
      return {
        content: [{ type: "text", text: "Report ready in Kraki's report viewer." }],
        // The adapter consumes this local path and stores the bytes as an
        // attachment. The HTML itself is deliberately never returned to pi.
        details: { htmlPath: abs, title: requestedTitle, name: abs.split(/[\\/]/).pop() || "report.html" },
      };
    },
  });

  pi.registerTool({
    name: "kraki_get_mode",
    label: "Get Kraki mode",
    description:
      "Return the current Kraki permission mode (safe|auto|delegate). " +
      "safe = file changes, shell commands and external tools need operator " +
      "approval (reads/searches run freely); auto/delegate = all tools run without " +
      "approval. Call this before irreversible actions.",
    promptGuidelines: [
      "Call kraki_get_mode before irreversible or destructive actions (deleting " +
      "files, force-pushing, destructive shell) to confirm the operator has " +
      "granted you permission to act.",
    ],
    parameters: {
      type: "object",
      properties: {
        query: {
          type: "string",
          enum: ["current"],
          description: "Request the current Kraki permission mode.",
        },
      },
      required: ["query"],
      additionalProperties: false,
    },
    async execute() {
      let mode = "auto";
      try {
        const p = process.env.KRAKI_META_FILE;
        if (p) {
          const meta = JSON.parse(readFileSync(p, "utf8"));
          if (meta && typeof meta.mode === "string") mode = meta.mode;
        }
        // Sidecars written before the three-mode rename.
        if (mode === "execute") mode = "auto";
      } catch (_err) {
        // fall back to the default on any read/parse failure
      }
      return { content: [{ type: "text", text: mode }], details: { mode } };
    },
  });

  // Permission gate — ask the host to confirm every non-capability tool. Loaded
  // in ALL modes and always firing; the ADAPTER decides (via its copilot-aligned
  // policy on the live mode) whether to auto-approve silently or raise a card.
  pi.on("tool_call", async (event, ctx) => {
    const toolName = event && event.toolName;
    if (!toolName || KRAKI_TOOLS.has(toolName)) return;
    // No dialog channel available (shouldn't happen in rpc mode). Fail open so
    // the session isn't wedged waiting on a prompt that can never be answered.
    if (!ctx || !ctx.hasUI) return;
    const input = (event && event.input) || {};
    if (toolName === "bash") {
      const command = typeof input.command === "string" ? input.command : "";
      if (krakiIsSelfManagement(command)) {
        return {
          block: true,
          reason: "Denied by Kraki: kraki stop, restart, and update cannot run inside an agent session because they would terminate the tentacle hosting this session."
        };
      }
    }
    let message;
    try {
      message = JSON.stringify(input);
    } catch (_err) {
      message = "{}";
    }
    const approved = await ctx.ui.confirm(toolName, message);
    if (!approved) {
      return { block: true, reason: "Denied by user \u2014 " + toolName + " was not run (kraki permission)." };
    }
  });
}
`;
