/**
 * Source of the "kraki tools" pi extension — the single extension the pi adapter
 * always loads (`--extension`). It gives pi Kraki's human-interaction tools plus
 * the per-call permission gate:
 *
 *   • `ask_user(question, choices?)` — blocks until the human answers and
 *     returns their answer as the tool result. Surfaces via `ctx.ui.select`
 *     (choices) / `ctx.ui.input` (free-form), which in `--mode rpc` emit an
 *     `extension_ui_request` the adapter maps to a Kraki question card; the
 *     answer returns as an `extension_ui_response`.
 *   • `finalize_reply({resummarize, text?})` — the turn-conclusion tool. The
 *     adapter injects a "finalize your turn" prompt at the end of a turn that
 *     dropped intermediate narration; the model calls this ONCE to either keep
 *     its drafted closing line (`resummarize:false`) or replace it with a short
 *     rewritten summary (`resummarize:true, text`). NOT for spontaneous use —
 *     ordinary assistant prose already streams to the human as the reply.
 *   • `kraki_get_mode({query:"current"})` — returns the live Kraki permission mode
 *     (safe|discuss|execute|delegate), read from the meta sidecar the adapter
 *     exports as `KRAKI_META_FILE`. Lets the model confirm its permission
 *     envelope before irreversible actions (the adapter is the source of truth).
 *   • permission gate — intercepts every OTHER tool and asks
 *     `ctx.ui.confirm(...)`. The gate is loaded in ALL modes and always fires;
 *     the ADAPTER decides (via its copilot-aligned `shouldAutoApprove` policy on
 *     the live mode) whether to auto-approve silently or raise a Kraki card. The
 *     capability tools (ask_user / finalize_reply / show_image / kraki_get_mode)
 *     are whitelisted so they are never permission-prompted (they ARE the human
 *     channel / read-only introspection).
 *
 * Kept as a string constant (not a separate asset) so it survives the tentacle
 * SEA bundle — esbuild inlines it and the adapter materializes it to disk at
 * runtime. `parameters` are plain JSON Schema objects (verified accepted by pi
 * 0.80.2) so the materialized file needs no `typebox` import it couldn't resolve.
 */
export const PI_KRAKI_TOOLS_SOURCE = String.raw`// AUTO-GENERATED by the Kraki pi adapter. Do not edit by hand.
// Registers ask_user + finalize_reply + show_image + kraki_get_mode (Kraki's
// human-interaction & introspection tools) and a per-call permission gate that
// asks the host to confirm every other tool; the adapter applies the mode policy.
import { readFileSync } from "node:fs";
import { isAbsolute, join } from "node:path";
// Capability tools never go through the permission gate — they carry their own
// operator interaction (ask_user/show_image), settle the turn (finalize_reply),
// or are read-only introspection (kraki_get_mode).
const KRAKI_TOOLS = new Set(["ask_user", "finalize_reply", "show_image", "kraki_get_mode"]);

export default function krakiTools(pi) {
  pi.registerTool({
    name: "ask_user",
    label: "Ask the user",
    description:
      "Ask the human operator a question and BLOCK until they answer. Returns the " +
      "user's answer as the tool result. Provide 'choices' for a multiple-choice " +
      "question, or omit them for a free-form answer.",
    promptGuidelines:
      "Use ask_user whenever you need a decision, clarification, or missing " +
      "information from the user. The return value is their literal answer.",
    parameters: {
      type: "object",
      properties: {
        question: { type: "string", description: "The question to ask the user." },
        choices: { type: "array", items: { type: "string" }, description: "Optional multiple-choice options." },
      },
      required: ["question"],
      additionalProperties: false,
    },
    async execute(_id, params, _signal, _onUpdate, ctx) {
      const q = String((params && params.question) || "");
      const choices = params && Array.isArray(params.choices) ? params.choices : null;
      if (!ctx || !ctx.hasUI) {
        return { content: [{ type: "text", text: "(no UI available to ask the user)" }], details: {} };
      }
      let answer;
      if (choices && choices.length) {
        answer = await ctx.ui.select(q, choices);
      } else {
        answer = await ctx.ui.input(q, "");
      }
      const text = answer == null ? "(the user did not answer)" : String(answer);
      return { content: [{ type: "text", text }], details: { answer: text } };
    },
  });

  pi.registerTool({
    name: "finalize_reply",
    label: "Finalize reply",
    description:
      "Conclude the current turn. The Kraki runtime asks you to call this at the " +
      "end of a turn to settle the final message shown to the user. If the drafted " +
      "closing line quoted in the prompt is already a good final message, call " +
      "finalize_reply({ resummarize: false }). Otherwise call finalize_reply({ " +
      "resummarize: true, text: \"<a short, self-contained, plain-text final " +
      "message>\" }). Only call this when the runtime asks you to finalize \u2014 " +
      "your ordinary prose already reaches the user as the reply.",
    promptGuidelines:
      "Do NOT call finalize_reply on your own initiative. It is invoked only in " +
      "response to the runtime's finalize prompt, exactly once, to keep or rewrite " +
      "the turn's closing message.",
    parameters: {
      type: "object",
      properties: {
        resummarize: { type: "boolean", description: "true to provide a rewritten summary in 'text'; false to keep the drafted closing line." },
        text: { type: "string", description: "The rewritten final message (required when resummarize is true)." },
      },
      required: ["resummarize"],
      additionalProperties: false,
    },
    async execute() {
      return { content: [{ type: "text", text: "Turn finalized." }], details: {} };
    },
  });

  pi.registerTool({
    name: "show_image",
    label: "Show image to user",
    description:
      "Display an image to the user in the Kraki chat. Use this to visually present " +
      "something the user cannot already see \u2014 a screenshot, diagram, chart, or " +
      "generated graphic. Provide the path to an image file on disk (PNG, JPEG, WebP, " +
      "GIF). For images you only need to inspect yourself, use the read tool instead.",
    promptGuidelines:
      "Only call show_image when the user would gain new information from seeing the " +
      "image (e.g. a chart or diagram you just generated). Do NOT echo back an image " +
      "the user just sent you \u2014 they can already see it.",
    parameters: {
      type: "object",
      properties: {
        path: { type: "string", description: "Absolute or cwd-relative path to the image file to display." },
        caption: { type: "string", description: "Optional caption shown with the image." },
      },
      required: ["path"],
      additionalProperties: false,
    },
    async execute(_id, params) {
      const p = String((params && params.path) || "");
      const caption = params && params.caption ? String(params.caption) : "";
      if (!p) {
        return { content: [{ type: "text", text: "show_image: no path provided" }], isError: true, details: {} };
      }
      const abs = isAbsolute(p) ? p : join(process.cwd(), p);
      let bytes;
      try {
        bytes = readFileSync(abs);
      } catch (err) {
        const msg = (err && err.message) || String(err);
        return { content: [{ type: "text", text: "show_image: cannot read " + abs + " \u2014 " + msg }], isError: true, details: {} };
      }
      const ext = (abs.split(".").pop() || "").toLowerCase();
      const mimeType =
        ext === "png" ? "image/png" :
        ext === "webp" ? "image/webp" :
        ext === "gif" ? "image/gif" : "image/jpeg";
      const content = [];
      if (caption) content.push({ type: "text", text: caption });
      content.push({ type: "image", data: bytes.toString("base64"), mimeType });
      return { content, details: { shown: abs, mimeType } };
    },
  });

  pi.registerTool({
    name: "kraki_get_mode",
    label: "Get Kraki mode",
    description:
      "Return the current Kraki permission mode (safe|discuss|execute|delegate). " +
      "safe = every tool needs operator approval; discuss = only file writes need " +
      "approval (reads/shell run freely, writes to plan.md are allowed); execute/" +
      "delegate = all tools run without approval. Call this before irreversible actions.",
    promptGuidelines:
      "Call kraki_get_mode before irreversible or destructive actions (deleting " +
      "files, force-pushing, destructive shell) to confirm the operator has " +
      "granted you permission to act.",
    parameters: {
      type: "object",
      properties: {
        query: {
          type: "string",
          enum: ["current"],
          description: "Request the current Kraki permission mode.",
        },
      },
      required: ["query"],
      additionalProperties: false,
    },
    async execute() {
      let mode = "discuss";
      try {
        const p = process.env.KRAKI_META_FILE;
        if (p) {
          const meta = JSON.parse(readFileSync(p, "utf8"));
          if (meta && typeof meta.mode === "string") mode = meta.mode;
        }
      } catch (_err) {
        // fall back to the default on any read/parse failure
      }
      return { content: [{ type: "text", text: mode }], details: { mode } };
    },
  });

  // Permission gate — ask the host to confirm every non-capability tool. Loaded
  // in ALL modes and always firing; the ADAPTER decides (via its copilot-aligned
  // policy on the live mode) whether to auto-approve silently or raise a card.
  pi.on("tool_call", async (event, ctx) => {
    const toolName = event && event.toolName;
    if (!toolName || KRAKI_TOOLS.has(toolName)) return;
    // No dialog channel available (shouldn't happen in rpc mode). Fail open so
    // the session isn't wedged waiting on a prompt that can never be answered.
    if (!ctx || !ctx.hasUI) return;
    const input = (event && event.input) || {};
    if (toolName === "bash") {
      const command = typeof input.command === "string" ? input.command : "";
      if (/\bkraki\s+(?:stop|restart|update)\b/i.test(command)) {
        return {
          block: true,
          reason: "Denied by Kraki: kraki stop, restart, and update cannot run inside an agent session because they would terminate the tentacle hosting this session."
        };
      }
    }
    let message;
    try {
      message = JSON.stringify(input);
    } catch (_err) {
      message = "{}";
    }
    const approved = await ctx.ui.confirm(toolName, message);
    if (!approved) {
      return { block: true, reason: "Denied by user \u2014 " + toolName + " was not run (kraki permission)." };
    }
  });
}
`;
