/**
 * Source of the "kraki permission gate" pi extension.
 *
 * pi has no built-in per-call tool-approval round-trip in `--mode rpc`; its
 * only interactive primitive is the extension UI `confirm` dialog. To align pi
 * with the claude/copilot adapters — where the user approves each mutating
 * tool in `discuss`/`safe` mode instead of losing the tool entirely — the pi
 * adapter loads this extension (via `--extension`) only in the gated modes.
 *
 * The extension intercepts every `tool_call`, lets read-only tools through, and
 * for anything mutating asks `ctx.ui.confirm(...)`. In rpc mode that confirm is
 * emitted as an `extension_ui_request` the adapter turns into a normal Kraki
 * permission card; the user's decision comes back as an `extension_ui_response`
 * which resolves the confirm to allow or `{ block: true }`.
 *
 * Kept as a string constant (not a separate asset) so it survives the tentacle
 * SEA bundle — esbuild inlines it and the adapter materializes it to disk at
 * runtime. The tool name is passed as the confirm `title` and the tool input as
 * the JSON `message`, so the adapter can render a rich card and key the
 * response back to this exact request.
 */
export const PI_PERMISSION_GATE_SOURCE = String.raw`// AUTO-GENERATED by the Kraki pi adapter. Do not edit by hand.
// Per-call permission gate: prompts before every mutating tool in
// discuss/safe modes. Read-only tools pass through untouched.
const READONLY_TOOLS = new Set(["read", "grep", "find", "ls"]);

export default function krakiPermissionGate(pi) {
  pi.on("tool_call", async (event, ctx) => {
    const toolName = event && event.toolName;
    if (!toolName || READONLY_TOOLS.has(toolName)) return;
    // No dialog channel available (shouldn't happen in rpc mode). Fail open so
    // the session isn't wedged waiting on a prompt that can never be answered.
    if (!ctx || !ctx.hasUI) return;
    const input = (event && event.input) || {};
    let message;
    try {
      message = JSON.stringify(input);
    } catch (_err) {
      message = "{}";
    }
    const approved = await ctx.ui.confirm(toolName, message);
    if (!approved) {
      return { block: true, reason: "Denied by user \u2014 " + toolName + " was not run (kraki permission)." };
    }
  });
}
`;
