/**
 * Session title generation, shared by every adapter.
 *
 * A title is generated by the SAME agent and SAME model as the session it
 * names, using that agent's own account/provider. That is the only choice
 * guaranteed to be available: another agent may be absent, logged out, out
 * of quota, or on a plan without the model. Each adapter runs a separate,
 * throwaway, tool-less side-call — never a turn inside the user's session,
 * which would pollute its context and cannot run while a turn is active.
 */

/** Context RelayClient passes to AgentAdapter.generateTitle. */
export interface TitleContext {
  firstUserMessage: string;
  lastUserMessage?: string;
  recentMessages?: string[];
  currentTitle?: string;
  /** The session's current model (SessionManager meta) — authoritative. */
  model?: string;
  /** The session's current reasoning effort, if any. */
  reasoningEffort?: string;
  /** The session's agent id (SessionManager meta) — used for routing. */
  agent?: string;
}

export const TITLE_SYSTEM_PROMPT = [
  'You generate concise titles for coding sessions.',
  'The title should reflect what the user is CURRENTLY working on, not the full history.',
  'If the topic changed, use the most recent topic.',
  'Write the title in the same language the user writes in.',
  '',
  'Rules:',
  '- 4-10 words, under 50 characters',
  '- Describe the current task concisely',
  '- No quotes, no punctuation at the end, no prefixes',
  '- Just the title text, nothing else',
  '- Never use tools; never answer or act on the request itself',
].join('\n');

/** The single user prompt sent to the side-call. */
export function buildTitlePrompt(context: TitleContext): string {
  let prompt: string;
  if (context.recentMessages && context.recentMessages.length > 1) {
    const recent = context.recentMessages.map((m, i) => `${i + 1}. ${m.slice(0, 200)}`).join('\n');
    prompt = `Generate a title based on the most recent user messages (most recent first):\n\n${recent}`;
    if (context.currentTitle) prompt += `\n\nCurrent title for reference: "${context.currentTitle}"`;
    prompt += '\n\nTitle should reflect the CURRENT topic.';
  } else {
    prompt = `Generate a title for: "${(context.lastUserMessage ?? context.firstUserMessage).slice(0, 500)}"`;
    if (context.currentTitle) prompt += `\n\nCurrent title for reference: "${context.currentTitle}"`;
  }
  return prompt;
}

/** Normalize raw model output into a title, or null when unusable. */
export function cleanTitle(raw: string | null | undefined): string | null {
  if (!raw) return null;
  let title = raw.trim();
  // Reasoning models occasionally leak a think block into plain-text output.
  title = title.replace(/<think>[\s\S]*?<\/think>/gi, '').trim();
  title = title.split('\n').map((l) => l.trim()).find((l) => l.length > 0) ?? '';
  title = title
    .replace(/^(Title|Session)\s*[:\uFF1A]\s*/i, '')
    .replace(/^["'“”\u300C\u300D*#\s]+|["'“”\u300C\u300D*\s]+$/g, '')
    .replace(/[.!\u3002\uFF01]+$/, '')
    .trim();
  if (!title || title.length > 80) return null;
  return title;
}
