use tauri::{
    image::Image,
    menu::{Menu, MenuItem, PredefinedMenuItem},
    tray::{TrayIcon, TrayIconBuilder},
    App, AppHandle, Manager,
};

use crate::status::DaemonStatus;

// Tray icon PNG bytes — generated by scripts/gen-icons.mjs
const ICON_CONNECTED: &[u8] = include_bytes!("../icons/tray-connected.png");
const ICON_CONNECTING: &[u8] = include_bytes!("../icons/tray-connecting.png");
const ICON_DISCONNECTED: &[u8] = include_bytes!("../icons/tray-disconnected.png");

pub fn setup_tray(app: &mut App) -> tauri::Result<()> {
    let menu = build_menu(app, &DaemonStatus::default())?;
    let icon = Image::from_bytes(ICON_DISCONNECTED)?;

    TrayIconBuilder::with_id("kraki-tray")
        .icon(icon)
        .icon_as_template(true) // macOS: render as template (adapts to light/dark menu bar)
        .tooltip("Kraki")
        .menu(&menu)
        .on_menu_event(|app, event| handle_menu_event(app, event.id.as_ref()))
        .build(app)?;

    Ok(())
}

fn build_menu(app: &AppHandle, status: &DaemonStatus) -> tauri::Result<Menu<tauri::Wry>> {
    let version = env!("CARGO_PKG_VERSION");
    let relay_label = status_label(status);
    let toggle_label = if status.daemon_running && status.relay_state == "connected" {
        "Disconnect"
    } else {
        "Connect"
    };

    Menu::with_items(
        app,
        &[
            &MenuItem::with_id(app, "header", format!("Kraki v{version}"), false, None::<&str>)?,
            &MenuItem::with_id(app, "status", relay_label, false, None::<&str>)?,
            &PredefinedMenuItem::separator(app)?,
            &MenuItem::with_id(app, "toggle", toggle_label, true, None::<&str>)?,
            &MenuItem::with_id(app, "pair", "Pair new device…", true, None::<&str>)?,
            &PredefinedMenuItem::separator(app)?,
            &PredefinedMenuItem::quit(app, Some("Quit Kraki"))?,
        ],
    )
}

fn status_label(status: &DaemonStatus) -> String {
    if !status.daemon_running {
        return "○  Stopped".to_string();
    }
    match status.relay_state.as_str() {
        "connected" => "●  Connected".to_string(),
        "connecting" | "authenticating" => "◌  Connecting…".to_string(),
        _ => "○  Disconnected".to_string(),
    }
}

fn handle_menu_event(app: &AppHandle, id: &str) {
    match id {
        "toggle" => {
            let status = crate::status::read_status();
            if status.daemon_running && status.relay_state == "connected" {
                let _ = tauri::async_runtime::block_on(crate::commands::stop_daemon_inner(app));
            } else {
                let _ = tauri::async_runtime::block_on(crate::commands::start_daemon_inner(app));
            }
        }
        "pair" => open_qr_window(app),
        _ => {}
    }
}

fn open_qr_window(app: &AppHandle) {
    if let Some(win) = app.get_webview_window("qr") {
        let _ = win.show();
        let _ = win.set_focus();
    }
}

pub fn update_tray(app: &AppHandle, status: &DaemonStatus) {
    let Some(tray) = app.tray_by_id("kraki-tray") else {
        return;
    };

    // Update icon
    let icon_bytes = match status.relay_state.as_str() {
        "connected" => ICON_CONNECTED,
        "connecting" | "authenticating" => ICON_CONNECTING,
        _ => ICON_DISCONNECTED,
    };
    if let Ok(icon) = Image::from_bytes(icon_bytes) {
        let _ = tray.set_icon(Some(icon));
    }

    // Rebuild menu with fresh labels
    if let Ok(menu) = build_menu(app, status) {
        let _ = tray.set_menu(Some(menu));
    }

    // Update tooltip
    let tip = match status.relay_state.as_str() {
        "connected" => "Kraki — Connected",
        "connecting" | "authenticating" => "Kraki — Connecting…",
        _ => "Kraki — Disconnected",
    };
    let _ = tray.set_tooltip(Some(tip));
}
