/**
 * Session titles are generated by the session's OWN agent and model, as a
 * tool-less side-call. Never by "the first registered adapter".
 */
import { afterEach, beforeEach, describe, expect, it, vi } from 'vitest';
import { chmodSync, mkdtempSync, readFileSync, rmSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { AgentAdapter } from '../adapters/base.js';
import { MultiAgentAdapter } from '../adapters/multi.js';
import { CopilotAdapter } from '../adapters/copilot.js';
import { PiAdapter } from '../adapters/pi.js';
import { CodexAdapter } from '../adapters/codex.js';
import { buildTitlePrompt, cleanTitle, TITLE_SYSTEM_PROMPT } from '../adapters/title.js';

let dir: string;
beforeEach(() => { dir = mkdtempSync(join(tmpdir(), 'kraki-title-')); });
afterEach(() => { rmSync(dir, { recursive: true, force: true }); });

describe('title helpers', () => {
  it('cleans model output into a single short title', () => {
    expect(cleanTitle('"Fix flaky stats tests."')).toBe('Fix flaky stats tests');
    expect(cleanTitle('Title: Refactor auth\nextra line')).toBe('Refactor auth');
    expect(cleanTitle('<think>hmm</think>\n\u4FEE\u590D stats.py \u6D4B\u8BD5\u7528\u4F8B\u3002')).toBe('\u4FEE\u590D stats.py \u6D4B\u8BD5\u7528\u4F8B');
    expect(cleanTitle('**Kraki Codex adapter**')).toBe('Kraki Codex adapter');
    expect(cleanTitle('')).toBeNull();
    expect(cleanTitle('x'.repeat(81))).toBeNull();
  });

  it('builds a recent-first prompt that keeps the current title as reference', () => {
    const p = buildTitlePrompt({ firstUserMessage: 'a', recentMessages: ['newest', 'older'], currentTitle: 'Old' });
    expect(p).toContain('1. newest');
    expect(p).toContain('Current title for reference: "Old"');
    expect(TITLE_SYSTEM_PROMPT).toMatch(/same language/);
  });
});

class FakeAdapter extends AgentAdapter {
  generateTitle = vi.fn(async () => `title from ${this.name}`);
  constructor(readonly name: string) { super(); }
  async start() {} async stop() {}
  async createSession() { return { sessionId: 'x' }; }
  async resumeSession(id: string) { return { sessionId: id }; }
  async sendMessage() {} async respondToPermission() {}
  async respondToQuestion() { return 'accepted' as const; }
  async killSession() {} async listSessions() { return []; }
}

describe('MultiAgentAdapter title routing', () => {
  function multi() {
    const m = new MultiAgentAdapter({});
    const copilot = new FakeAdapter('copilot');
    const pi = new FakeAdapter('pi');
    const internals = m as unknown as { adapters: Map<string, AgentAdapter> };
    internals.adapters.set('copilot', copilot); // registered FIRST, like production
    internals.adapters.set('pi', pi);
    return { m, copilot, pi };
  }

  it('routes to the session agent, never to the first registered adapter', async () => {
    const { m, copilot, pi } = multi();
    const ctx = { firstUserMessage: 'hi', agent: 'pi', model: 'deepseek/deepseek-flash' };
    expect(await m.generateTitle('s1', ctx)).toBe('title from pi');
    expect(pi.generateTitle).toHaveBeenCalledWith('s1', ctx);
    expect(copilot.generateTitle).not.toHaveBeenCalled();
  });

  it('falls back to the known session→agent mapping when context has no agent', async () => {
    const { m, copilot, pi } = multi();
    m.registerSessionAgent('s2', 'pi');
    await m.generateTitle('s2', { firstUserMessage: 'hi' });
    expect(pi.generateTitle).toHaveBeenCalled();
    expect(copilot.generateTitle).not.toHaveBeenCalled();
  });

  it('returns null instead of borrowing another agent when the session agent is unavailable', async () => {
    const { m, copilot, pi } = multi();
    expect(await m.generateTitle('s3', { firstUserMessage: 'hi', agent: 'claude' })).toBeNull();
    expect(await m.generateTitle('s4', { firstUserMessage: 'hi' })).toBeNull();
    expect(copilot.generateTitle).not.toHaveBeenCalled();
    expect(pi.generateTitle).not.toHaveBeenCalled();
  });
});

describe('CopilotAdapter title', () => {
  function fixture(content = '"Fix stats tests."') {
    const adapter = new CopilotAdapter();
    const sendAndWait = vi.fn(async () => ({ data: { content } }));
    const client = {
      createSession: vi.fn(async () => ({ sessionId: 'throwaway', sendAndWait, disconnect: vi.fn(async () => {}) })),
      deleteSession: vi.fn(async () => {}),
    };
    const internals = adapter as unknown as { client: unknown; userRequestedModels: Map<string, string>; nativeTitles: Map<string, string> };
    internals.client = client;
    return { adapter, client, internals, sendAndWait };
  }

  it("uses Copilot's own native title without spending a request", async () => {
    const { adapter, client, internals } = fixture();
    internals.nativeTitles.set('s1', 'Native Copilot title');
    expect(await adapter.generateTitle('s1', { firstUserMessage: 'x', model: 'auto' })).toBe('Native Copilot title');
    expect(client.createSession).not.toHaveBeenCalled();
  });

  it('otherwise runs a tool-less side-call on the session model and rejects every permission', async () => {
    const { adapter, client } = fixture();
    expect(await adapter.generateTitle('s1', { firstUserMessage: 'fix stats', model: 'auto' })).toBe('Fix stats tests');
    const cfg = (client.createSession.mock.calls[0] as unknown[])[0] as Record<string, unknown>;
    expect(cfg).toMatchObject({ model: 'auto', availableTools: [] });
    expect((cfg.onPermissionRequest as () => unknown)()).toEqual({ kind: 'reject' });
    expect(client.deleteSession).toHaveBeenCalledWith('throwaway');
  });
});

describe('PiAdapter title', () => {
  it("runs a one-shot `pi --print` on the session's provider/model with everything off", async () => {
    const argvFile = join(dir, 'argv.json');
    const fakePi = join(dir, 'pi');
    writeFileSync(fakePi, `#!${process.execPath}\nrequire('fs').writeFileSync(${JSON.stringify(argvFile)}, JSON.stringify(process.argv.slice(2)));\nprocess.stdout.write('\u4FEE\u590D stats.py \u6D4B\u8BD5\\n');\n`);
    chmodSync(fakePi, 0o755);
    const pi = new PiAdapter({ cliPath: fakePi });
    const title = await pi.generateTitle('s1', { firstUserMessage: '\u5E2E\u6211\u4FEE\u6D4B\u8BD5', model: 'deepseek/deepseek-flash' });
    expect(title).toBe('\u4FEE\u590D stats.py \u6D4B\u8BD5');
    const argv = JSON.parse(readFileSync(argvFile, 'utf8')) as string[];
    for (const flag of ['--print', '--no-session', '--no-tools', '--no-extensions', '--no-skills', '--no-prompt-templates', '--no-context-files']) {
      expect(argv).toContain(flag);
    }
    expect(argv.slice(argv.indexOf('--provider'), argv.indexOf('--provider') + 2)).toEqual(['--provider', 'deepseek']);
    expect(argv.slice(argv.indexOf('--model'), argv.indexOf('--model') + 2)).toEqual(['--model', 'deepseek-flash']);
    expect(argv.slice(argv.indexOf('--thinking'), argv.indexOf('--thinking') + 2)).toEqual(['--thinking', 'off']);
    expect(argv.at(-1)).toContain('\u5E2E\u6211\u4FEE\u6D4B\u8BD5');
  });

  it('returns null (no title) when pi fails', async () => {
    const fakePi = join(dir, 'pi-fail');
    writeFileSync(fakePi, `#!${process.execPath}\nprocess.stderr.write('No API key');\nprocess.exit(1);\n`);
    chmodSync(fakePi, 0o755);
    const pi = new PiAdapter({ cliPath: fakePi });
    expect(await pi.generateTitle('s1', { firstUserMessage: 'x', model: 'p/m' })).toBeNull();
  });
});

describe('CodexAdapter title', () => {
  const FAKE = join(dirname(fileURLToPath(import.meta.url)), '..', 'adapters', '__tests__', 'fixtures', 'fake-codex-app-server.mjs');
  let codex: CodexAdapter;
  afterEach(async () => { await codex?.stop(); });

  function wire(): () => Array<{ method?: string; params?: Record<string, unknown>; result?: Record<string, unknown> }> {
    const log = join(dir, 'wire.jsonl');
    codex = new CodexAdapter({ cliPath: process.execPath, cliArgs: [FAKE], sessionsDir: join(dir, 'sessions'), env: { ...process.env, FAKE_CODEX_LOG: log }, requestTimeoutMs: 5000 });
    return () => readFileSync(log, 'utf8').trim().split('\n').map((l) => JSON.parse(l));
  }

  it('uses an ephemeral thread on the session model at its lowest effort, outside the session', async () => {
    const wireLog = wire();
    await codex.start();
    const { sessionId } = await codex.createSession({ cwd: dir, model: 'gpt-6-astra' });
    codex.onMessage = vi.fn(); codex.onIdle = vi.fn();
    expect(await codex.generateTitle(sessionId, { firstUserMessage: 'fix stats', model: 'gpt-6-astra' })).toBe('Fix flaky stats tests');
    const starts = wireLog().filter((m) => m.method === 'thread/start');
    expect(starts).toHaveLength(2);
    expect(starts[1].params).toMatchObject({ ephemeral: true, model: 'gpt-6-astra', approvalPolicy: 'untrusted', sandbox: 'read-only', baseInstructions: TITLE_SYSTEM_PROMPT });
    expect(starts[1].params!.dynamicTools).toBeUndefined();
    const turn = wireLog().filter((m) => m.method === 'turn/start').at(-1)!;
    expect(turn.params).toMatchObject({ model: 'gpt-6-astra', effort: 'low' });
    // Nothing leaks into the user's session.
    expect(codex.onMessage).not.toHaveBeenCalled();
    expect(codex.onIdle).not.toHaveBeenCalled();
  });

  it('declines any command the title thread tries to run', async () => {
    const wireLog = wire();
    await codex.start();
    const { sessionId } = await codex.createSession({ cwd: dir, model: 'gpt-6-astra' });
    const title = await codex.generateTitle(sessionId, { firstUserMessage: 'TRYTOOL' });
    expect(title).toBe('Title after decline');
    expect(wireLog().some((m) => !m.method && m.result?.decision === 'decline')).toBe(true);
  });
});
